function Convert-SQLProcedureToQVS {
    <#
    .SYNOPSIS
        Converts a SQL stored procedures INSERT statements to use #temp tables in order for QlikView to use the script.
    .DESCRIPTION
        Parses CREATE TABLE scripts from the project Tables folder,
        finds INSERT INTO statements in the given stored procedure,
        generates matching CREATE TABLE #temp definitions, and writes a new .qvs file.
    .PARAMETER Path
        Root path of the SQL project (contains Tables and StoredProcedures folders).
    .PARAMETER ProcedureName
        The base name of the stored procedure file (without .sql extension).
    .PARAMETER ProcedureSchema
        The name of the stored procedures schema.
    .PARAMETER ProcedureSchema
        If the file is a Table, View or Stored Procedure.
    .PARAMETER OutputFilePath
        The full path to the output QVS file to generate.
    .PARAMETER $Translations 
        The PSCustomObject $translations retrieved from Get-SQLToQVTranslations
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string] $Path,
        [Parameter(Mandatory = $true)]
        [PSCustomObject] $file,
        [Parameter(Mandatory = $true)]
        [string] $OutputFilePath,
        [Parameter(Mandatory = $true)]
        [PSCustomObject] $Translations
    )
    if ($file.Reason -eq "Drop") {
        Write-Host "?..Proposing to delete $($file.Name)"
        return 
    }
    switch ($file.FileType.ToLower()) {
        "sqlview"          { $fileFolder = "Views" }
        "sqlprocedure"  { $fileFolder = "Stored Procedures" }
        default         { 
            Write-Warning "Convert-SQLProcedureToQVS: Unknown procedure type '$($file.FileType)'. Using default folder 'Stored Procedures'."
            $fileFolder = "Stored Procedures"
        }
    }

    $ProceduresFolder = [System.IO.Path]::Combine($Path, $file.Schema, $fileFolder) 
    if (-not (Test-Path $ProceduresFolder)) {
        throw "Convert-SQLProcedureToQVS: StoredProcedures folder ej fundet: $ProceduresFolder"
    }    

    # Find stored procedure og GET indhold
    $procFile = Get-ChildItem -Path $ProceduresFolder -Filter "$($file.Name).sql" -Recurse | Select-Object -First 1
    if (-not $procFile) {
        throw "Convert-SQLProcedureToQVS: Stored procedure '$($file.Name).sql' ej fundet i $ProceduresFolder"
    }
    $procSql = Get-Content $procFile.FullName -Raw
    $tableDefinitions, $tableQVDefinitions = Get-SQLTableDefinitions -Path $Path

    switch ($file.FileType.ToLower()) {
        "sqlview" { 
            $procSql = Remove-SQLSyntaxView -ViewDefinition $procSql -IntoTableName $file.Name 
            $tempTableDefinitions = ""
        }
        "sqlprocedure"{ 
            $procSql = Remove-SQLSyntaxStoredProcedure -procedureDefinitions $procSql
            $tempTableDefinitions = Invoke-CreateTempTable -procSql $procSql -tableDefinitions $tableDefinitions                  
        }
        default         { 
            Write-Warning "Convert-SQLProcedureToQVS: Unknown procedure type '$($file.FileType)'. Can't remove syntax for unknown procedure."
            throw
        }
    }
   
    # Genererer output
    $output = @()
    $output += "-- ==========================================="
    $output += "-- Auto-generated by Convert-SQLToQVS"
    $output += "-- Source: $($file.Schema ).$($file.Name).sql"
    $output += "-- Latest reason for update: $($file.Reason)"
    $output += "-- ===========================================`n"

    $output += $tempTableDefinitions
    $output += $procSql    
    
    #Oversætter til temptables i QV
    foreach ($table in $tableDefinitions.Keys) {
        $output = $output -replace [regex]::Escape($table), $tableQVDefinitions[$table]
    }
    #Oversætter explorationtabeller(manuelt)
    foreach ($translation in $Translations) {
        $output = $output -replace [regex]::Escape($translation.SQLName), $translation.QVName
    }

    $outDir = Split-Path $OutputFilePath -Parent
    if (-not (Test-Path $outDir)) {
        New-Item -ItemType Directory -Path $outDir | Out-Null
    }

    Set-Content -Path $OutputFilePath -Value ($output -join "`r`n")

    Write-Host "? .. Created qvs fil: $OutputFilePath"
}
Export-ModuleMember Convert-SQLProcedureToQVS




function Remove-SQLSyntaxStoredProcedure {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [PSCustomObject] $procedureDefinitions
    )
    #Tager kun fra Begin transaction til Commit Transaction
    $procedureDefinitions = $procedureDefinitions -creplace '(?i)truncate table .*\r?\n?', ''
    $procedureDefinitions = $procedureDefinitions -replace "[\[\]]", ""

    $pattern = "(?is)BEGIN TRANSACTION(.*?)COMMIT TRANSACTION"
    $patternMatch = [regex]::Matches($procedureDefinitions, $pattern)
   
    $extractedContent = $patternMatch.Groups[1].Value
    return $extractedContent
}

function Remove-SQLSyntaxView {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [PSCustomObject] $ViewDefinition,
        [Parameter(Mandatory = $true)]
        [string] $IntoTableName
    )
    $ViewDefinition = $ViewDefinition -replace "[\[\]]", ""

    $pattern = "(?is)CREATE\s+VIEW\s+\S+\s+AS\s+(.*)"
    $patternMatch = [regex]::Matches($ViewDefinition, $pattern)
   
    $extractedContent = $patternMatch.Groups[1].Value
    $extractedContent = $extractedContent -replace "(?i)\bFROM\b", "INTO #$($IntoTableName) `nFROM"
    return $extractedContent
}



Function Get-SQLTableDefinitions {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string] $Path
    )
    $tableDefinitions = @{}
    $tableQVDefinitions = @{}

    Get-ChildItem -Path $Path -Filter '*.sql' -Recurse | ForEach-Object {
        $content = Get-Content $_.FullName -Raw
        # --- CREATE TABLE ---
        $tablePattern = 'CREATE\s+TABLE\s+(?:\[(?<schema>[A-Za-z0-9_]+)\]|\b(?<schema>[A-Za-z0-9_]+)\b)?\s*\.\s*(?:\[(?<table>[A-Za-z0-9_]+)\]|\b(?<table>[A-Za-z0-9_]+)\b)\s*\((?<cols>[\s\S]*?)\)\s*;'
        if ($content -match $tablePattern) {
            $schema = if ($matches['schema']) { $matches['schema'] } else { 'dbo' }
            $table  = $matches['table']
            $columnsFull = $matches['cols'].Trim()
            $columns = ($columnsFull -split "`r?`n" | Where-Object {
                $line = $_.Trim()
                -not ($line -match '^(PRIMARY\s+KEY|FOREIGN\s+KEY|CONSTRAINT|UNIQUE|CHECK)\b')
            }) -join "`n"
            $key = "$schema.$table".ToLowerInvariant()
            $tableDefinitions[$key] = $columns
            $tableQVDefinitions[$key] = "#$key" -replace "\.", "_"
        }

        # --- CREATE VIEW ---
        $viewPattern = 'CREATE\s+VIEW\s+(?:\[(?<schema>[A-Za-z0-9_]+)\]|\b(?<schema>[A-Za-z0-9_]+)\b)?\s*\.\s*(?:\[(?<view>[A-Za-z0-9_]+)\]|\b(?<view>[A-Za-z0-9_]+)\b)\s+AS\s+(?<body>[\s\S]*?)(?:;|$)'
        if ($content -match $viewPattern) {
            $schema = if ($matches['schema']) { $matches['schema'] } else { 'dbo' }
            $view   = $matches['view']
            $key = "$schema.$view".ToLowerInvariant()
            $tableDefinitions[$key] = $null 
            $tableQVDefinitions[$key] = "#$key" -replace "\.", "_"
        }
    }

    if ($tableDefinitions.Count -eq 0) {
        throw "Get-SQLTableDefinitions: No CREATE TABLE or VIEW definitions found in $Path"
    }
    return $tableDefinitions, $tableQVDefinitions
}


Function Invoke-CreateTempTable {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string] $procSql,
        [Parameter(Mandatory = $true)]
        [hashtable] $tableDefinitions
    )
    $tableInsertMatches = [regex]::Matches(
        $procSql,
        'INSERT\s+INTO\s+(?:\[(?<schema>[A-Za-z0-9_]+)\]|\b(?<schema>[A-Za-z0-9_]+)\b)?\s*\.?\s*(?:\[(?<table>[A-Za-z0-9_]+)\]|\b(?<table>[A-Za-z0-9_]+)\b)', #Robot-RegEX
        'IgnoreCase'
    )

    $uniqueTables = @{}

    foreach ($match in $tableInsertMatches) {
        $schema = $match.Groups['schema'].Value
        $tableName = $match.Groups['table'].Value

        if (-not $schema) {
            $schema = $ProcedureSchema
        }

        $key = "$schema.$tableName".ToLowerInvariant()

        if ($tableDefinitions.ContainsKey($key) -and -not $uniqueTables.ContainsKey($tableName)) {
            $uniqueTables["$schema.$tableName"] = $key
        }
    }

    # Byg CREATE TABLE for alle unikke forekomster af tabellen
    $tempTableDefinitions = @()
    foreach ($tableName in $uniqueTables.Keys) {
        $key = $uniqueTables[$tableName]
        $cols = $tableDefinitions[$key]
        $tempTableDefinitions += "CREATE TABLE $tableName (`n$cols`n);`n"
    }
    return $tempTableDefinitions
}


